apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: kaas
  name: kaas
  namespace: kaas
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: kaas:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: main
      uri: https://github.com/vrutkovs/kaas
    type: Git
  strategy:
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ImageChange
  - type: ConfigChange
  - type: "GitHub"
    github:
      secret: "secret101"
