apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: kaas
  name: static-kas
  namespace: kaas
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: kaas:static-kas
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: hypershift
      uri: https://github.com/stbenjam/static-kas
    dockerfile: |
      FROM registry.ci.openshift.org/openshift/release:golang-1.17 AS builder
      WORKDIR /go/src/github.com/alvaroaleman/static-kas
      COPY . .
      RUN go mod vendor && go build -o ./static-kas ./cmd/

      FROM registry.access.redhat.com/ubi8/ubi-minimal:8.5
      COPY --from=builder /go/src/github.com/alvaroaleman/static-kas/static-kas /bin/static-kas
      WORKDIR /srv
      ENTRYPOINT ["/bin/static-kas"]
    type: Git
  strategy:
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ImageChange
  - type: ConfigChange
  - type: "GitHub"
    github:
      secret: "secret101"
